default_language_version:
    python: python3.8
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-builtin-literals
    -   id: check-ast
    -   id: check-json
    -   id: detect-private-key
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black

-   repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort

        args: [--profile=black]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks.
  autofix_prs: true
  autoupdate_branch: "master"
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
